server:
  address: "tcp://0.0.0.0:9091"

identity_validation:
  reset_password:
    jwt_secret: <<FILE:/secrets/JWT_SECRET

authentication_backend:
  ldap:
    implementation: lldap
    address: ldap://lldap:3890
    timeout: 5s
    start_tls: false
    base_dn: dc=rwa,dc=local
    additional_users_dn: ou=people
    users_filter: "(&({username_attribute}={input})(objectClass=person))"
    additional_groups_dn: ou=groups
    groups_filter: "(member={dn})"
    user: uid=admin,ou=people,dc=rwa,dc=local
    password: password123

session:
  secret: <<FILE:/secrets/SESSION_SECRET
  name: authelia_session
  same_site: lax
  expiration: 1h
  inactivity: 5m
  remember_me: 1M
  cookies:
    - domain: 127.0.0.1
      authelia_url: https://127.0.0.1:9091
      default_redirection_url: https://127.0.0.1/administration/
  redis:
    host: redis
    port: 6379

storage:
  encryption_key: <<FILE:/secrets/STORAGE_ENCRYPTION_KEY
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

access_control:
  default_policy: deny
  rules:
    # Разрешаем доступ к API проверки (нужно для Nginx)
    - domain: "*"
      resources: ["^/api/verify.*$"]
      policy: bypass

    # Доступ к RabbitMQ только для группы admin_rabbitmq
    - domain: "*"
      resources: ["^/administration/rabbitmq/.*$"]
      subject: "group:admin_rabbitmq"
      policy: one_factor

    # Доступ к Mongo Express только для группы admin_mongodb
    - domain: "*"
      resources: ["^/administration/mongo-express/.*$"]
      subject: "group:admin_mongodb"
      policy: one_factor

    # Все остальные разделы администрирования доступны любому вошедшему юзеру
    - domain: "*"
      resources: ["^/administration/.*$"]
      policy: one_factor

    # Доступ к основному домену (если нужно)
    - domain: "*"
      policy: one_factor
