type ApiKey {
  id: ID!
  name: String!
  prefix: String!
  userId: String!
  wallet: String!
  createdAt: Int!
  updatedAt: Int!
}

type CreateApiKeyResult {
  id: ID!
  name: String!
  prefix: String!
  key: String!
  createdAt: Int!
}

input CreateApiKeyInput {
  name: String!
}

input UpdateApiKeyInput {
  id: ID!
  name: String!
}

extend type Query {
  getApiKeys: [ApiKey!]!
  getApiKey(id: ID!): ApiKey!
}

extend type Mutation {
  createApiKey(input: CreateApiKeyInput!): CreateApiKeyResult!
  updateApiKey(input: UpdateApiKeyInput!): ApiKey!
  deleteApiKey(id: ID!): ID!
}
