import { edenTreaty } from '@elysiajs/eden';
import { Redis } from 'ioredis';
import { CONFIG } from '../config';
import type { App as AuthApp } from '@services/auth/src';
import type { App as AiAssistantApp } from '@services/ai-assistant/src';
import type { App as TestnetFaucetApp } from '@services/testnet-faucet/src';
import type { App as RwaApp } from '@services/rwa/src';
import type { App as FilesApp } from '@services/files/src';
import type { App as SignersManagerApp } from '@services/signers-manager/src';
import type { App as DocumentsApp } from '@services/documents/src';
import type { App as GalleryApp } from '@services/gallery/src';
import type { App as QuestionsApp } from '@services/questions/src';
import type { App as FaqApp } from '@services/faq/src';
import type { App as BlogApp } from '@services/blog/src';
import type { App as PortfolioApp } from '@services/portfolio/src';
import type { App as CompanyApp } from '@services/company/src';
import type { App as ChartsApp } from '@services/charts/src';
import type { App as ReactionsApp } from '@services/reactions/src';
import type { App as LoyaltyApp } from '@services/loyalty/src';

export const authClient = edenTreaty<AuthApp>(CONFIG.SERVICES.AUTH.URL);
export const aiAssistantClient = edenTreaty<AiAssistantApp>(CONFIG.SERVICES.ASSISTANT.URL);
export const testnetFaucetClient = edenTreaty<TestnetFaucetApp>(CONFIG.SERVICES.TESTNET_FAUCET.URL);
export const rwaClient = edenTreaty<RwaApp>(CONFIG.SERVICES.RWA.URL);
export const filesClient = edenTreaty<FilesApp>(CONFIG.SERVICES.FILES.URL);
export const signersManagerClient = edenTreaty<SignersManagerApp>(CONFIG.SERVICES.SIGNERS_MANAGER.URL);
export const documentsClient = edenTreaty<DocumentsApp>(CONFIG.SERVICES.DOCUMENTS.URL);
export const galleryClient = edenTreaty<GalleryApp>(CONFIG.SERVICES.GALLERY.URL);
export const questionsClient = edenTreaty<QuestionsApp>(CONFIG.SERVICES.QUESTIONS.URL);
export const faqClient = edenTreaty<FaqApp>(CONFIG.SERVICES.FAQ.URL);
export const blogClient = edenTreaty<BlogApp>(CONFIG.SERVICES.BLOG.URL);
export const portfolioClient = edenTreaty<PortfolioApp>(CONFIG.SERVICES.PORTFOLIO.URL);
export const companyClient = edenTreaty<CompanyApp>(CONFIG.SERVICES.COMPANY.URL);
export const chartsClient = edenTreaty<ChartsApp>(CONFIG.SERVICES.CHARTS.URL);
export const reactionsClient = edenTreaty<ReactionsApp>(CONFIG.SERVICES.REACTIONS.URL);
export const loyaltyClient = edenTreaty<LoyaltyApp>(CONFIG.SERVICES.LOYALTY.URL);

export type AuthClient = typeof authClient;
export type AiAssistantClient = typeof aiAssistantClient;
export type TestnetFaucetClient = typeof testnetFaucetClient;
export type RwaClient = typeof rwaClient;
export type FilesClient = typeof filesClient;
export type SignersManagerClient = typeof signersManagerClient;
export type DocumentsClient = typeof documentsClient;
export type GalleryClient = typeof galleryClient;
export type QuestionsClient = typeof questionsClient;
export type FaqClient = typeof faqClient;
export type BlogClient = typeof blogClient;
export type PortfolioClient = typeof portfolioClient;
export type CompanyClient = typeof companyClient;
export type ChartsClient = typeof chartsClient;
export type ReactionsClient = typeof reactionsClient;
export type LoyaltyClient = typeof loyaltyClient;
