import { Redis } from 'ioredis';
import { CONFIG } from '../config';
import { trace, propagation, context } from '@opentelemetry/api';
import type { App as AuthApp } from '@services/auth/src';
import type { App as AiAssistantApp } from '@services/ai-assistant/src';
import type { App as TestnetFaucetApp } from '@services/testnet-faucet/src';
import type { App as RwaApp } from '@services/rwa/src';
import type { App as FilesApp } from '@services/files/src';
import type { App as SignersManagerApp } from '@services/signers-manager/src';
import type { App as DocumentsApp } from '@services/documents/src';
import type { App as GalleryApp } from '@services/gallery/src';
import type { App as QuestionsApp } from '@services/questions/src';
import type { App as FaqApp } from '@services/faq/src';
import type { App as BlogApp } from '@services/blog/src';
import type { App as PortfolioApp } from '@services/portfolio/src';
import type { App as CompanyApp } from '@services/company/src';
import type { App as ChartsApp } from '@services/charts/src';
import type { App as ReactionsApp } from '@services/reactions/src';
import type { App as LoyaltyApp } from '@services/loyalty/src';
import type { App as DaoApp } from '@services/dao/src';

import { logger } from "@shared/monitoring/src/logger";
import { createEdenTreatyClient } from "@shared/monitoring/src/eden";


export const authClient = createEdenTreatyClient<AuthApp>(CONFIG.SERVICES.AUTH.URL);
export const aiAssistantClient = createEdenTreatyClient<AiAssistantApp>(CONFIG.SERVICES.ASSISTANT.URL);
export const testnetFaucetClient = createEdenTreatyClient<TestnetFaucetApp>(CONFIG.SERVICES.TESTNET_FAUCET.URL);
export const rwaClient = createEdenTreatyClient<RwaApp>(CONFIG.SERVICES.RWA.URL);
export const filesClient = createEdenTreatyClient<FilesApp>(CONFIG.SERVICES.FILES.URL);
export const signersManagerClient = createEdenTreatyClient<SignersManagerApp>(CONFIG.SERVICES.SIGNERS_MANAGER.URL);
export const documentsClient = createEdenTreatyClient<DocumentsApp>(CONFIG.SERVICES.DOCUMENTS.URL);
export const galleryClient = createEdenTreatyClient<GalleryApp>(CONFIG.SERVICES.GALLERY.URL);
export const questionsClient = createEdenTreatyClient<QuestionsApp>(CONFIG.SERVICES.QUESTIONS.URL);
export const faqClient = createEdenTreatyClient<FaqApp>(CONFIG.SERVICES.FAQ.URL);
export const blogClient = createEdenTreatyClient<BlogApp>(CONFIG.SERVICES.BLOG.URL);
export const portfolioClient = createEdenTreatyClient<PortfolioApp>(CONFIG.SERVICES.PORTFOLIO.URL);
export const companyClient = createEdenTreatyClient<CompanyApp>(CONFIG.SERVICES.COMPANY.URL);
export const chartsClient = createEdenTreatyClient<ChartsApp>(CONFIG.SERVICES.CHARTS.URL);
export const reactionsClient = createEdenTreatyClient<ReactionsApp>(CONFIG.SERVICES.REACTIONS.URL);
export const loyaltyClient = createEdenTreatyClient<LoyaltyApp>(CONFIG.SERVICES.LOYALTY.URL);
export const daoClient = createEdenTreatyClient<DaoApp>(CONFIG.SERVICES.DAO.URL);

export type AuthClient = typeof authClient;
export type AiAssistantClient = typeof aiAssistantClient;
export type TestnetFaucetClient = typeof testnetFaucetClient;
export type RwaClient = typeof rwaClient;
export type FilesClient = typeof filesClient;
export type SignersManagerClient = typeof signersManagerClient;
export type DocumentsClient = typeof documentsClient;
export type GalleryClient = typeof galleryClient;
export type QuestionsClient = typeof questionsClient;
export type FaqClient = typeof faqClient;
export type BlogClient = typeof blogClient;
export type PortfolioClient = typeof portfolioClient;
export type CompanyClient = typeof companyClient;
export type ChartsClient = typeof chartsClient;
export type ReactionsClient = typeof reactionsClient;
export type LoyaltyClient = typeof loyaltyClient;
export type DaoClient = typeof daoClient;
