/**
 * In-memory fake of OpenRouterClient (shared/openrouter/client.ts).
 *
 * The services only use chatCompletion() for AI field generation. This fake
 * returns the same response shape as the real client
 * (choices[0].message.content) and lets tests configure the content:
 * `setChatCompletionContent(content)` - pass a string to control parsing,
 * null to simulate a response without content (choices: []).
 */
import { mock } from 'bun:test';

export const DEFAULT_CHAT_COMPLETION_CONTENT = '{"name":"AI Business","tags":["ai"],"description":"Generated by AI"}';

export type FakeChatCompletionRequest = {
  model: string;
  messages: Array<{ role: string; content: string }>;
};

export function createFakeOpenRouterClient(initialContent: string | null = DEFAULT_CHAT_COMPLETION_CONTENT) {
  let chatCompletionContent = initialContent;

  const client = {
    chatCompletion: mock(async (request: FakeChatCompletionRequest) => ({
      id: 'chatcmpl-test',
      model: request.model,
      choices:
        chatCompletionContent === null
          ? []
          : [{ index: 0, message: { role: 'assistant', content: chatCompletionContent } }],
    })),

    completion: mock(async (_request: unknown) => ({ id: 'cmpl-test', choices: [] })),

    setChatCompletionContent(content: string | null) {
      chatCompletionContent = content;
    },
  };

  return client;
}

export type FakeOpenRouterClient = ReturnType<typeof createFakeOpenRouterClient>;
